# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
language: node_js

import:
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml
  - .travis/.travis_depth_1.yml

jobs:
  include:
    - stage: Merge
      script:
        - echo "helloworld"
